created policies with Pundit and updated CRUD features
APatel-AI/industrial-auth-1 pull request #2
Opened 2024-07-18 11:22 UTC by APatel-AI

2024-07-18 14:08 UTC, dylansarikas commented on app/controllers/follow_requests_controller.rb
> +    def authorize_follow_request
nice job creating this method and calling it in a before action

2024-07-18 14:08 UTC, dylansarikas reviewed
looks good arpan!

2024-07-18 14:09 UTC, dylansarikas approved these changes

2024-07-18 14:10 UTC, dylansarikas approved these changes

2024-07-22 21:04 UTC, ajmompr requested changes
Fix the policy that you are calling in users#show. Add missing before action to your comments controller

2024-07-22 21:04 UTC, ajmompr commented on app/controllers/application_controller.rb
> +  after_action :verify_authorized, unless: :devise_controller?
good job accounting for devise

2024-07-22 21:04 UTC, ajmompr commented on app/controllers/comments_controller.rb
>    before_action :set_comment, only: %i[ show edit update destroy ]
missing before_action to authorize comment policy. How are you ensuring a user is authorized to comment?

2024-07-22 21:04 UTC, ajmompr commented on app/controllers/follow_requests_controller.rb
> +  before_action :authorize_follow_request, only: [:show, :edit, :update, :destroy]
good

2024-07-22 21:04 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +  before_action :authorize_photo, only: [:show, :edit, :update, :destroy]
good

2024-07-22 21:04 UTC, ajmompr commented on app/controllers/users_controller.rb
> +  before_action {authorize @user || User}
great! You can use similar before actions across all of your controllers. This is more concise.

2024-07-22 21:04 UTC, ajmompr commented on app/controllers/users_controller.rb
> +      authorize @user
if calling before_action {authorize @user || User}, authorize @ user becomes redundant

2024-07-22 21:04 UTC, ajmompr commented on app/policies/like_policy.rb
not needed for this assignment

2024-07-22 21:04 UTC, ajmompr commented on app/policies/user_policy.rb
perfect

2024-07-22 21:04 UTC, ajmompr commented on app/views/users/show.html.erb
> +<% if policy(@user).show? %>
should be calling show_photos?

2024-07-23 17:26 UTC, ajmompr approved these changes

2024-07-23 17:26 UTC, ajmompr commented on app/controllers/comments_controller.rb
> +  before_action {authorize @comment || Comment}
good

2024-07-23 17:37 UTC, merged

2024-08-18 00:58 UTC, FadiBaker92 reviewed
code looks clean. Good job Arpan!